"""process_rebirth.py — обработать share-беседу при перерождении агента.

Сохраняет выгрузку в logs/<роль>/conversations/, нумерует, чистит
от мусора (UI-строки, дубли).

Запуск:
    python process_rebirth.py --role B --url https://chat.deepseek.com/share/xxx
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def next_number(folder):
    if not folder.exists():
        return 1
    nums = []
    for f in folder.glob("*.md"):
        m = re.match(r"^(\d+)_", f.name)
        if m:
            nums.append(int(m.group(1)))
    return max(nums) + 1 if nums else 1


def clean(text):
    """Убрать мусор: строки-UI, пустые подряд, служебные метки."""
    lines = text.splitlines()
    out = []
    for ln in lines:
        s = ln.strip()
        # служебные строки LLM
        if s in ("Thought for a few seconds", "Thought for 1 second"):
            continue
        if s.startswith("This shared conversation is generated by AI"):
            continue
        if s == "Shared Conversation":
            out.append(s); continue
        if not s:
            if out and out[-1] == "":
                continue
            out.append("")
            continue
        out.append(ln)
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--role", required=True, help="A/B/C/D...")
    ap.add_argument("--url", required=True)
    ap.add_argument("--port", type=int, default=9223)
    ap.add_argument("--wait", type=float, default=12.0)
    a = ap.parse_args()

    role = a.role.upper()
    folder = ROOT / "logs" / role / "conversations"
    folder.mkdir(parents=True, exist_ok=True)
    n = next_number(folder)
    raw = folder / f"_{n}_raw.md"
    final = folder / f"{n:03d}_share.md"

    cmd = [sys.executable, str(ROOT / "sandbox" / "export_share.py"),
           "--url", a.url, "--out", str(raw),
           "--port", str(a.port), "--wait", str(a.wait)]
    r = subprocess.run(cmd, capture_output=True, text=True,
                       encoding="utf-8", errors="replace")
    if r.returncode != 0 or not raw.exists():
        print("FAIL export:", r.stderr[:300])
        return 1

    txt = raw.read_text(encoding="utf-8", errors="replace")
    txt = clean(txt)
    final.write_text(txt, encoding="utf-8")
    raw.unlink()

    # запись в README папки
    readme = folder / "README.md"
    line = f"- {final.name} — выгрузка {a.url}, {len(txt)} байт\n"
    if readme.exists():
        readme.write_text(readme.read_text(encoding="utf-8") + line, encoding="utf-8")
    else:
        readme.write_text("# Беседы агента " + role + "\n\n" + line, encoding="utf-8")

    print("OK", final, len(txt), "bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())