// pers.js - вкладка Персональные (Борис 3B)
let persCh=null,persLastTs=0;
const PERS_NAMES={A:"Аркадий",B:"Борис",C:"Семён",D:"Дима"};
const PERS_COLORS={A:"#00ff66",B:"#33d6ff",C:"#c573ff",D:"#ffb000"};
function persInit(){const w=document.getElementById("persList");if(!w)return;w.innerHTML="";["A","B","C","D"].forEach(k=>{const b=document.createElement("div");b.className="pers-item";b.dataset.ch=k;b.textContent=PERS_NAMES[k]||k;b.style.color=PERS_COLORS[k];b.addEventListener("click",()=>persSelect(k));w.appendChild(b);});}
async function persSelect(ch){persCh=ch;persLastTs=0;document.getElementById("persTitle").textContent=PERS_NAMES[ch]||ch;document.getElementById("persFeed").textContent="";document.querySelectorAll(".pers-item").forEach(e=>e.classList.toggle("active",e.dataset.ch===ch));await persPoll();}
async function persPoll(){if(!persCh)return;try{const r=await fetch("/api/chat/"+persCh,{cache:"no-store"});if(!r.ok)return;const d=await r.json();const feed=document.getElementById("persFeed");(d.messages||[]).forEach(m=>{if(m.ts<=persLastTs)return;persLastTs=m.ts;const div=document.createElement("div");div.className="pers-msg";const h=document.createElement("span");h.className="pers-h";h.textContent=(m.id||"")+" "+(m.from==="operator"?"Вы":(PERS_NAMES[m.from]||m.from))+": ";div.appendChild(h);const t=document.createElement("span");t.textContent=m.text;div.appendChild(t);feed.appendChild(div);});feed.scrollTop=feed.scrollHeight;}catch(e){}}
async function persSend(){if(!persCh)return;const inp=document.getElementById("persInput");const t=inp.value.trim();if(!t)return;inp.value="";try{await fetch("/api/chat/"+persCh,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({from:"operator",text:t})});await persPoll();}catch(e){}}
window.addEventListener("DOMContentLoaded",()=>{if(!document.getElementById("persList"))return;persInit();const s=document.getElementById("persSend");if(s)s.addEventListener("click",persSend);const i=document.getElementById("persInput");if(i)i.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();persSend();}});setInterval(persPoll,3000);});
